---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Add Homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew_taps }}"
    state: present
  when: homebrew_taps is defined and homebrew_taps | length > 0

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ homebrew_formulae }}"
    state: present
  when: homebrew_formulae is defined and homebrew_formulae | length > 0

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew_casks }}"
    state: present
  when: homebrew_casks is defined and homebrew_casks | length > 0
