---
dotfiles_packages:
  - aerospace
  - git
  - hushlogin
  - iterm2
  - neovim
  - zsh
  - zed

homebrew_formulae:
  - wget
  - tree
  - eza
  - bat
  - fzf
  - zoxide
  - htop
  - fastfetch
  - watch
  - neovim
  - tmux
  - git
  - go
  - node
  - python@3.14
  - openjdk@21
  - ripgrep
  - cloc
  - ascii-image-converter
  - iperf3
  - ffmpeg
  - yt-dlp
  - FelixKratz/formulae/borders

homebrew_casks:
  # WM
  - nikitabobko/tap/aerospace

  # Develop
  - iterm2
  - visual-studio-code
  - zed
  - docker-desktop
  - bruno

  # QoL
  - obsidian
  - hammerspoon
  - maccy
  - betterdisplay
  - aldente
  - shottr
  - zen
  - utm
  - bitwarden
  - netnewswire
  - iina
  - anki

  # Utils
  - neohtop
  - coconutbattery
  - appcleaner
  - keka
  - mac-mouse-fix
  - keyboardcleantool
