---
ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

project_root: "{{ inventory_dir | dirname }}"
dotfiles_dir: "{{ project_root }}/dotfiles"
